### ISSUE TITLE
cronjob fails

### ISSUE THREAD

**Issue by goern** [thoth-station/cleanup-job#1]
```

/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
--
  | InsecureRequestWarning)
  | Traceback (most recent call last):
  | File "/app.py", line 100, in <module>
  | sys.exit(main())
  | File "/app.py", line 95, in main
  | analyzers = _get_analyzers()
  | File "/app.py", line 49, in _get_analyzers
  | response.raise_for_status()
  | File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://kubernetes.default.svc.cluster.local//api/v1/namespaces//thoth-test-core/pods?labelSelector=thothtype%3Duserpod

```

**Comment by fridex** [comment]
Is `KUBERNETES_VERIFY_TLS` env variable set to "0"?

**Comment by goern** [comment]
ja

**Comment by fridex** [comment]
How did you run it? Was is a periodic job or was it triggered from user API?

**Comment by goern** [comment]
It was a cronjob https://github.com/goern/thoth-core/blob/master/openshift/template.yaml#L324
